### ISSUE TITLE
Bank to Pokemon

### ISSUE THREAD

**Issue by aulee888** [Victorli888/Pokemon#2]
Logged into PC and selected the Bank option.

Bank option said it is in development and then it took me to choosing three different pokemon.

![image](https://user-images.githubusercontent.com/58223643/89831213-4adb4600-db12-11ea-948c-da335ba8cde4.png)

**Comment by Victorli888** [comment]
Issue Adressed: PC had Pass values that would skip to the next function in story.py (which is poke_selection)
